// AUTO-GENERATED by scripts/import-whitepaper.mjs — do not edit by hand.
// Source: Autonomous.docx
// Regenerate: node scripts/import-whitepaper.mjs <path-to.docx>

/** Words in atonomosDocument, for the hub's read-time estimate. */
export const atonomosWordCount = 10677
