// AUTO-GENERATED by scripts/import-document.mjs — do not edit by hand.
// Source: Autonomous.docx
// Regenerate: node scripts/import-document.mjs <file> --slug atonomos

/** Words in atonomosDocument, for the hub's read-time estimate. */
export const atonomosWordCount = 19572
