import type { Content, Project } from '@/content/types'
import { atonomosWordCount } from '@/content/fixtures/atonomos.meta'

/**
 * Atonomos — the whitepaper project.
 *
 * The body is committed: the paper is published openly, so it lives in the
 * repository alongside its source document (`sources/Autonomous.docx`) and is
 * regenerated by `npm run whitepaper` rather than hand-maintained.
 */
export const atonomosWhitepaper: Content = {
  id: 'cnt_atonomos_read',
  type: 'ereader',
  ownerSlug: 'deanMaye',
  projectSlug: 'atonomos',
  title: 'Autonomous: The Agentic Enterprise',
  // An ereader Content has no items: its body is the document, not a list of
  // media files.
  published: true,
  totalDurationMs: 0,
  items: [],
  credits: [{ creatorSlug: 'deanMaye', name: 'Dean Maye', role: 'writer' }],
  /*
   * No `document` here. The prose is ~26 KB gzipped and was riding in the
   * initial bundle for every visitor, including the ones who never open the
   * reader. The adapter attaches it on demand in `getContent`; the hub uses
   * the word count below, which is all it ever needed.
   */
  wordCount: atonomosWordCount,
  // Mirrors this row's actual created_at in Supabase, so the feed orders
  // fixtures the same way it orders production.
  createdAt: '2026-08-27T19:27:44.713Z',
}

export const atonomos: Project = {
  id: 'prj_atonomos',
  ownerSlug: 'deanMaye',
  slug: 'atonomos',
  title: 'Atonomos',
  description:
    'A whitepaper on the agentic enterprise — how organisations restructure when agents become first-class operators rather than bolted-on automation.',
  published: true,
  contents: [atonomosWhitepaper],
}
