import type { Content, Project } from '@/content/types'
import { atonomosDocument } from '@/content/fixtures/atonomos.document'

/**
 * Atonomos — the whitepaper project.
 *
 * The body is committed: the paper is published openly, so it lives in the
 * repository alongside its source document (`sources/Autonomous.docx`) and is
 * regenerated by `npm run whitepaper` rather than hand-maintained.
 */
export const atonomosWhitepaper: Content = {
  id: 'cnt_atonomos_read',
  type: 'ereader',
  ownerSlug: 'dean',
  projectSlug: 'atonomos',
  title: 'Autonomous: The Agentic Enterprise',
  // An ereader Content has no items: its body is the document, not a list of
  // media files.
  published: true,
  totalDurationMs: 0,
  items: [],
  credits: [{ creatorSlug: 'dean', name: 'Dean', role: 'writer' }],
  document: atonomosDocument,
}

export const atonomos: Project = {
  id: 'prj_atonomos',
  ownerSlug: 'dean',
  slug: 'atonomos',
  title: 'Atonomos',
  description: 'A whitepaper on the agentic enterprise — how organisations restructure when agents become first-class operators rather than bolted-on automation.',
  published: true,
  contents: [atonomosWhitepaper],
}
