// AUTO-GENERATED by scripts/gen-fixtures.mjs — do not edit by hand.
// Source: ./Bronze (gitignored, unmastered rough mixes).
// Regenerate: npm run fixtures

import type { Content, Creator } from '@/content/types'

export const dean: Creator = {
  id: 'crt_robotrebel',
  slug: 'robotrebel',
  name: 'robotrebel',
  bio: 'Technology executive, venture investor, and strategic advisor with 15+ years leading enterprise transformation, AI innovation, and technology-enabled value creation across Fortune 500 enterprises, venture-backed and growth-staged businesses. Combines executive leadership, investment perspective, and deep technical expertise to accelerate business transformation and performance.',
  // Mirrors the seed in 20260821020000_creator_profile.sql so fixtures and
  // Supabase render the same profile.
  socials: { linkedin: 'https://www.linkedin.com/in/odeanmaye/' },
  tier: 'standard',
  subdomain: null,
  customDomain: null,
}

export const bronze: Content = {
  id: 'cnt_bronze',
  type: 'music',
  ownerSlug: 'robotrebel',
  slug: 'bronze',
  title: 'Bronze',
  published: false,
  totalDurationMs: 2272825,
  credits: [{ creatorSlug: 'robotrebel', name: 'robotrebel', role: 'artist' }],
  items: [
    {
      "id": "itm_01",
      "position": 1,
      "title": "Bronze Age (Skit)",
      "isInterlude": true,
      "credits": [],
      "hash": "54350c3939798715",
      "bytes": 224828,
      "durationMs": 13009,
      "channels": 1,
      "sampleRate": 44100,
      "bitrate": 128000,
      "url": "/media/audio/01%20-%20Bronze%20Age%20(Skit).mp3"
    },
    {
      "id": "itm_02",
      "position": 2,
      "title": "Bronze",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "e4384bea4ab9f70f",
      "bytes": 5385119,
      "durationMs": 243912,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 175814,
      "url": "/media/audio/02%20-%20Bronze.mp3"
    },
    {
      "id": "itm_03",
      "position": 3,
      "title": "Let's Play A Game",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "0bdcdeac4b7f7b10",
      "bytes": 5190188,
      "durationMs": 222120,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 186346,
      "url": "/media/audio/03%20-%20Let_s%20Play%20A%20Game.mp3"
    },
    {
      "id": "itm_04",
      "position": 4,
      "title": "Kissy Face Emoji",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "c5b0a68381f00620",
      "bytes": 5221453,
      "durationMs": 230688,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 180171,
      "url": "/media/audio/04%20-%20Kissy%20Face%20Emoji.mp3"
    },
    {
      "id": "itm_05",
      "position": 5,
      "title": "Polished Bronze (Skit)",
      "isInterlude": true,
      "credits": [],
      "hash": "71600fe0b2bfe283",
      "bytes": 160462,
      "durationMs": 8986,
      "channels": 1,
      "sampleRate": 44100,
      "bitrate": 128000,
      "url": "/media/audio/05%20-%20Polished%20Bronze%20(Skit).mp3"
    },
    {
      "id": "itm_06",
      "position": 6,
      "title": "Summer Flame",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "fccbb84e9142880d",
      "bytes": 3432784,
      "durationMs": 152904,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 178639,
      "url": "/media/audio/06%20-%20Summer%20Flame.mp3"
    },
    {
      "id": "itm_07",
      "position": 7,
      "title": "Naked",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "8b0ee262ec087ab4",
      "bytes": 5316284,
      "durationMs": 234432,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 180792,
      "url": "/media/audio/07%20-%20Naked.mp3"
    },
    {
      "id": "itm_08",
      "position": 8,
      "title": "Bronze Alloy (Skit)",
      "isInterlude": true,
      "credits": [],
      "hash": "b88413d26035c7dd",
      "bytes": 173419,
      "durationMs": 9796,
      "channels": 1,
      "sampleRate": 44100,
      "bitrate": 128000,
      "url": "/media/audio/08%20-%20Bronze%20Alloy%20(Skit).mp3"
    },
    {
      "id": "itm_09",
      "position": 9,
      "title": "No Vacancy",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "e588baa91d34e304",
      "bytes": 3995374,
      "durationMs": 167280,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 190080,
      "url": "/media/audio/09%20-%20No%20Vacancy.mp3"
    },
    {
      "id": "itm_10",
      "position": 10,
      "title": "7.6 Say It",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "a475dd202c9c083e",
      "bytes": 10319168,
      "durationMs": 257976,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 320000,
      "url": "/media/audio/10%20-%207.6%20Say%20It.mp3"
    },
    {
      "id": "itm_11",
      "position": 11,
      "title": "Bronze Medal (Skit)",
      "isInterlude": true,
      "credits": [],
      "hash": "5d8583bd295443d7",
      "bytes": 188884,
      "durationMs": 10762,
      "channels": 1,
      "sampleRate": 44100,
      "bitrate": 128000,
      "url": "/media/audio/11%20-%20Bronze%20Medal%20(Skit).mp3"
    },
    {
      "id": "itm_12",
      "position": 12,
      "title": "8.10 Closure",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "c9ba8aede47a2f58",
      "bytes": 9431168,
      "durationMs": 235776,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 320000,
      "url": "/media/audio/12%20-%208.10%20Closure.mp3"
    },
    {
      "id": "itm_13",
      "position": 13,
      "title": "8.3 The Wait Is Over",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "38007b00c3d83f49",
      "bytes": 9510848,
      "durationMs": 237768,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 320000,
      "url": "/media/audio/13%20-%208.3%20The%20Wait%20Is%20Over.mp3"
    },
    {
      "id": "itm_14",
      "position": 14,
      "title": "8.3 Forevermore, I Pray",
      "isInterlude": false,
      "credits": [
        {
          "creatorSlug": "robotrebel",
          "name": "robotrebel",
          "role": "artist"
        }
      ],
      "hash": "3cb8ae61b6861275",
      "bytes": 9896768,
      "durationMs": 247416,
      "channels": 2,
      "sampleRate": 48000,
      "bitrate": 320000,
      "url": "/media/audio/14%20-%208.3%20Forevermore%2C%20I%20Pray.mp3"
    }
  ],
}
